Start shuffling the cross build bits out into a slightly more sensible location.
* start renaming variables
* start enforcing variables are exported/set as appropriate
* put distfiles in ${CUR_DIR}../distfiles/ rather than where they
  currently live inside the damned checkout directory.. oops.

diff --git a/port-build/scripts/cross_build b/port-build/scripts/cross_build
--- a/port-build/scripts/cross_build
+++ b/port-build/scripts/cross_build
@@ -6,6 +6,11 @@ SCRIPT_NAME="`basename $0`"
 SCRIPT_DIR="`dirname $0`"
 CUR_DIR="`pwd`"
 
+if [ "x${X_PACKAGE_ROOTDIR}" = "x" ]; then
+	echo "ERROR: need X_PACKAGE_ROOTDIR defined (for rootfs)."
+	exit 1
+fi
+
 . ${SCRIPT_DIR}/cross_build.subr
 
 # For now, let's just do this in one big hit, but
@@ -28,6 +33,13 @@ if [ "${X_PORTBUILD_PLATFORM}" != "mips" ]; then
 	echo "ERROR: for now, we only support mips."
 	exit 1
 fi
+
+# .. and distfiles
+if [ "x${X_PACKAGE_DISTFILE_DIR}" = "x" ]; then
+	echo "ERROR: need X_PACKAGE_DISTFILE_DIR defined."
+	exit 1
+fi
+
 
 X_PORTBUILD_PORT=$1
 shift
